### ISSUE TITLE
Public Development Version of Dashboard

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/cdm-bi#19]
Can you inform me when the public version of your dashboard will be available so we can continue the development @joaorafaelalmeida.

Thanks

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
I did not reply earlier because I am waiting for the server to be opened in the firewall, so that it can accessed by entities from outside the university. 
It has not been forgotten, and meanwhile, we have been working on system improvements based on your feedback from last month's workshop.

**Comment by joaorafaelalmeida** [comment]
This system is already installed under the https://superset.ehden.eu/login/ and https://dashboards.ehden.eu/ domains with dummy data. However, I am not sure If you have an user. I will continue this conversation by email to discuss the superset credentials.
